export * from './Minus';
export * from './Plus';
export * from './Cancel';
export * from './Check';
export * from './FilledStar';
export * from './Star';
export * from './Preview';
export * from './Edit';
export * from './Save';
export * from './Delete';
export * from './FileDownload';
export * from './Folder';
export * from './Play';
export * from './Upload';

export * from './DownArrow';
export * from './UpArrow';
export * from './RightArrow';
export * from './LeftArrow';
